# Generated by Django 4.1 on 2022-12-19 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shishaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flavor',
            options={'verbose_name': 'Flavor', 'verbose_name_plural': 'Flavors'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shishaApp.flavor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
