# Generated by Django 4.1 on 2022-12-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shishaApp', '0002_alter_flavor_options_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='imageLink',
            field=models.TextField(),
        ),
    ]
